title: 'blackthorne18.github.io'
baseurl: '/testsite2/' 
url: "https://blackthorne18.github.io"

header_pages:
  - index.md
  - about.md
  - work.md
  - scicom.md

style: dark
footer: 'PVB'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console 
